---
- hosts: all
  become: yes
  tasks: 
  - name: i wnat to install webserver
    apt: 
      name: apache2
      state: present
  - name: i want install tre
    apt:
      name: tree
      state: present    